language: python

env:
  global:
    # Doctr deploy key for pcdshub/transfocate
    - secure: "iCk6KU/1plL5t2zIHT8rbxOAFscxoMdYq/Uc8SxpFnoihg4yvhJdkYsYmvW1VLVg4WIPDohP0u0SU/HWIz8bXvxlv97Q9IeR674tqOK2JxT9+0DXDw3uWDaBHYwo/bPvTS8Rl9c/UN3QKsQgOp7G6F28g0sO7Gqtx43WnvDBDin1fXJEXlNU0efXQqFxg3syDELnizYOIhB66hojBHknmr6n8wllnVdIKP5HWdROQ1t73Ev2x6i/iopUlAqf0TzM7ykPkCbpNGBDGkwSxuoe3xKSpSbk2XTcSM92aGI8jZKosJ1f0WICuSrWGvIdwXxKQJgTIgTgxEP6Z/2zOmxSsfERbCCyEDe0RWwAXWbG5vh95HdEZzvtwnFi6zn9/HSRmtcBEbrYe3+Guww/Oz2nod7ooNDDFpqmIAwQGcV0U2pTiwUiQQf6tWa7Hiu4NFqrt8GFH9jh/+NfjPhc0jQfUcbiponqCRdXjOovX+FDIhDVgY1FDJF5uSAZkv4/C08s+ZpKt+JI9kVxGkK9qRub9T9J5usuOs/EXcmT4X8839bYvPEtzw5iS52sbQuYVjZRNDwyQOljz7M/q8daQDntoXPUYVQmMCgwszeuAPJOppxUalpiNyZ2lw0UGSzujK2sFUDjMZEBbcig1Oi0OJJD2WG3EiHEcxQtz8Ztf9Xfe1c="
    # enable the usage of versions menu which allow versioning of the docs
    # pages and not only the master branch
    - DOCTR_VERSIONS_MENU="1"
    # Dependency files used to build the documentation (space separated)
    - DOCS_REQUIREMENTS="dev-requirements.txt"
    # Options to be passed to flake8 for package linting. Usually this is just
    # the package name but you can enable other flake8 options via this config
    - PYTHON_LINT_OPTIONS="transfocate"

    # The name of the conda package
    - CONDA_PACKAGE="transfocate"
    # The folder containing the conda recipe (meta.yaml)
    - CONDA_RECIPE_FOLDER="conda-recipe"
    # Extra dependencies needed to run the tests which are not included
    # at the recipe and dev-requirements.txt. E.g. PyQt
    - CONDA_EXTRAS="pip"
    # Requirements file with contents for tests dependencies
    - CONDA_REQUIREMENTS="dev-requirements.txt"

    # Extra dependencies needed to run the test with Pip (similar to
    # CONDA_EXTRAS) but for pip
    - PIP_EXTRAS=""

jobs:
  allow_failures:
    - name: "Python 3.6 - PIP"
    - name: "Python Linter"

import:
  # This import enables a set of standard python jobs including:
  # - Build
  #   - Anaconda Package Build
  # - Tests
  #   - Python Linter
  #   - Package Linter
  #   - Documentation
  #   - Python 3.6 - PIP based
  #   - Python 3.6, 3.7 & 3.8 - Conda base
  # - Deploy
  #   - Documentation using doctr
  #   - Conda Package - uploaded to pcds-dev and pcds-tag
  #   - PyPI
  - pcdshub/pcds-ci-helpers:travis/shared_configs/standard-python-conda-latest.yml
