language: python

env:
  global:
    # Doctr deploy key for pcdshub/transfocate
    - secure: "O911a0S6mT2ZBsQ/CK0Bsi751gnNFjO2JprBOedvspbaosIYzGK5rP3b34ZcbndHJkrfFXo8lRQOmaVgwk2LMOwU86rvgvojVWtoUJ/CWOvkAlRo5480ZWqBrBuY0bs/sa3ufCP7knjzYGvoNYNx3LibPxRnCyOapAkdGI2JqhVeTjOywlA/EP9pJ8jPmJDI0mWUJRWgIna0u3n6BVEXHff8/CmG9r8SlfFDjr9nIY3L+eWIwx7tNja+qA3fr87XkQ74RaGbNhN/Ib4TY967b3QO2VbDkHxBCc/5HKmqgPiSaxIUqA1e/uAaR+F2UbmAfcwV8FCFJ4abjBCYLpHhyXwCiLrLmN1aPYp6//UKR964cvufSh5s5ZLMWQ+y4rEByiDoUkrQprd/h2p0roYaLD3lfK9FfRuN+U723Dd2+sQvoHkoCofYMUQHX06L0lHTgphjZbRKIIBqXCQKVsz3VX3ICXJieOQCG3xYWaaYiovpfDUcr00TlacwYtw+PnBhzRqHfZGX6I6mpX70p7EcGJY03wab2OGbAYHnBQpZsDRGQt2fSzX83aHxz0Y27MleW0/6J4FjCuZCFvlkYzI+7pIlc1RidmeTJ/5oRWhoM3K4DWKnAFyKx8YSAo0XiXAltmBW8foOtT/P5B1CcrcGMF/sVbDgElx1cvbfQyzLh64="
    # enable the usage of versions menu which allow versioning of the docs
    # pages and not only the master branch
    - DOCTR_VERSIONS_MENU="1"
    # Dependency files used to build the documentation (space separated)
    - DOCS_REQUIREMENTS="dev-requirements.txt"
    # Options to be passed to flake8 for package linting. Usually this is just
    # the package name but you can enable other flake8 options via this config
    - PYTHON_LINT_OPTIONS="transfocate"

    # The name of the conda package
    - CONDA_PACKAGE="transfocate"
    # The folder containing the conda recipe (meta.yaml)
    - CONDA_RECIPE_FOLDER="conda-recipe"
    # Extra dependencies needed to run the tests which are not included
    # at the recipe and dev-requirements.txt. E.g. PyQt
    - CONDA_EXTRAS="pip"
    # Requirements file with contents for tests dependencies
    - CONDA_REQUIREMENTS="dev-requirements.txt"

    # Extra dependencies needed to run the test with Pip (similar to
    # CONDA_EXTRAS) but for pip
    - PIP_EXTRAS=""

jobs:
  allow_failures:
    - name: "Python 3.6 - PIP"
    - name: "Python Linter"

import:
  # This import enables a set of standard python jobs including:
  # - Build
  #   - Anaconda Package Build
  # - Tests
  #   - Python Linter
  #   - Package Linter
  #   - Documentation
  #   - Python 3.6 - PIP based
  #   - Python 3.6, 3.7 & 3.8 - Conda base
  # - Deploy
  #   - Documentation using doctr
  #   - Conda Package - uploaded to pcds-dev and pcds-tag
  #   - PyPI
  - pcdshub/pcds-ci-helpers:travis/shared_configs/standard-python-conda.yml
