{% set package_name = "transfocate" %}
{% set import_name = "transfocate" %}
{% set version = load_file_regex(load_file=os.path.join(import_name, "_version.py"), regex_pattern=".*version = '(\S+)'").group(1) %}

package:
  name: {{ package_name }}
  version: {{ version }}

source:
  path: ..

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
  - python >=3.9
  - setuptools_scm
  - pip
  run:
  - python >=3.9
  - bluesky
  - databroker
  - matplotlib-base
  - numpy
  - openpyxl
  - ophyd >=1.5.0
  - pandas
  - pcdsdevices >=4.0.0
  - prettytable
  - reportlab

test:
  requires:
  - pytest
  imports:
  - transfocate

about:
  home: https://github.com/pcdshub/transfocate
  license: SLAC Open License
  summary: Devices abstractions and utlitiies for the MFX Transfocator
